import { Inter } from 'next/font/google'
import '@/styles/fonts/fonts.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><script src="http://localhost:8097"></script></head>
      <body className={inter.className} style={{ margin: 0 }} >{children}</body>
    </html>
  )
}
